---
- name: Download installer
  get_url:
    url: "{{ _nodejs_installer_download_url }}"
    dest: "{{ _nodejs_installer_download_dest }}"
    mode: 0744

- name: Add nodejs repository
  shell: "{{ _nodejs_installer_download_dest }}"
    
- name: Install packages
  apt:
    name: "{{ _nodejs_packages }}"