---
- name: Check if nodejs is installed
  stat:
    path: /usr/bin/node
  register: _nodejs_info

- name: Download installer
  get_url:
    url: "{{ _nodejs_installer_download_url }}"
    dest: /tmp/nodejs-installer.sh
  when: not _nodejs_info.stat.exists

- name: Install nodejs
  shell: /tmp/nodejs-installer.sh
  when: not _nodejs_info.stat.exists

- name: Delete nodejs installer
  file:
    path: /tmp/nodejs-installer.sh
    state: absent
  when: not _nodejs_info.stat.exists
    
- name: Install packages
  apt:
    name: "{{ _nodejs_packages }}"